### ISSUE TITLE
Markers are not centered around Lat/Lng 

### ISSUE THREAD

**Issue by MisterJimson** [giorgiabosello/google-maps-react-markers#269]
### Verify latest release

- [X] I verified that the issue exists in the latest release

### I know how to solve the bug

I don't know how to solve the bug and I will provide an example.

### Link to the code that reproduces this issue

https://giorgiabosello.github.io/google-maps-react-markers/

### To Reproduce

This is reproducible in the example project: https://giorgiabosello.github.io/google-maps-react-markers/

- Zoom out all the way
- View the markers

### Describe the Bug

Zoom out far, and it becomes clear the markers are offset from the lat/long. It seems like the top left of the marker may be roughy at the lat/lng, but the center or bottom of the marker is very far off at this zoom level. In the example below the marker is in the middle of the ocean after zooming out.

![image](https://github.com/giorgiabosello/google-maps-react-markers/assets/7351329/a44bbd50-6978-4b95-8fd0-754f8ce9f017)

![image](https://github.com/giorgiabosello/google-maps-react-markers/assets/7351329/abb7c994-4310-40ef-b4d3-c8316f27c860)

### Expected Behavior

Marker is clearly at the Lat/lng.

### Which browser are you using? (if relevant)

Chrome 125

**Comment by samwyzz** [comment]
Facing same problem, since marker components can vary in width and height, and the desired anchor point could be the top or bottom of the marker element, there should be a way to specify an offset for the marker relative to the lat,lng anchor point. Similar to how offset for overlays is handled in pigeon maps. https://pigeon-maps.js.org/docs/overlay/#offset

**Comment by giorgiabosello** [comment]
@MisterJimson This is fixed on version 2.0.10. Please, let me know.
@samwyzz Thank you for your input! Offset was the solution. 🫶🏼

**Comment by jhelmink** [comment]
In 2.0.10 I'm still seeing this issue, but I am resolving it using an offset for the Marker image itself using a transform style of negative half the image height. This might be a better alternative than moving the whole overlay? Because now I'm not sure if my GPS coordinates on the map are "true".
```
{
	const imgWidth = 36;
	const imgHeight = 36;

	return lat && lng ? (
		// eslint-disable-next-line @next/next/no-img-element, jsx-a11y/click-events-have-key-events, jsx-a11y/no-noninteractive-element-interactions
		<img
			className={className}
			src={`${process.env.NEXT_PUBLIC_MEDIA_URL ?? ''}/marker-pin${
				draggable ? '-draggable' : ''
			}.png`}
			// lat={lat}
			// lng={lng}
			onClick={(e) => (onClick ? onClick(e, { markerId, lat, lng }) : null)}
			style={{ fontSize: 40, transform: `translate(0px, ${-(imgHeight/2)}px)` }}
			alt={markerId}
			width={imgWidth}
			height={imgHeight}
			{...props}
		/>
	) : null
}
```

![image](https://github.com/user-attachments/assets/bb372f6b-3c70-4dab-8c4b-a31761414574)
